name: Build Windows Release
on: [workflow_dispatch] # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive # 必须拉取子模块

    - name: Setup and Install vcpkg & Dependencies
      run: |
        # 直接克隆微软官方 vcpkg
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        # 初始化 vcpkg
        .\bootstrap-vcpkg.bat
        # 安装 libcimbar 所需的依赖库
        .\vcpkg install opencv:x64-windows glfw3:x64-windows

    - name: Configure and Build libcimbar
      run: |
        mkdir build
        cd build
        # 引用刚才下载的 vcpkg 工具链进行 CMake 配置
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64
        # 开始多线程编译
        cmake --build . --config Release -j 4

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libcimbar-windows-exe
        path: build/Release/cimbar.exe
